-- Initial database schema for Morphine platform

-- User balances table
CREATE TABLE user_balances (
    user_id VARCHAR NOT NULL,
    stream_id VARCHAR NOT NULL,
    total_deposited DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    activation_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    betting_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    active_bets_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_winnings DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_losses DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    bet_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, stream_id)
);

-- Bets table
CREATE TABLE bets (
    id VARCHAR PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    stream_id VARCHAR NOT NULL,
    bet_type TEXT NOT NULL,
    stake_amount DECIMAL(10,2) NOT NULL,
    prediction JSONB NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    resolution_deadline TIMESTAMPTZ NOT NULL,
    resolution_result JSONB,
    potential_payout DECIMAL(10,2) NOT NULL,
    odds DECIMAL(10,4) NOT NULL
);

-- Streams table (for persistent stream metadata)
CREATE TABLE streams (
    id VARCHAR PRIMARY KEY,
    title VARCHAR NOT NULL,
    description TEXT,
    activation_threshold DECIMAL(10,2) NOT NULL,
    cost_per_viewer DECIMAL(10,2) NOT NULL,
    current_pledges DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    pledger_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB
);

-- Analytics events table (for storing computer vision results)
CREATE TABLE analytics_events (
    id SERIAL PRIMARY KEY,
    stream_id VARCHAR NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    event_type VARCHAR NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Betting opportunities table (generated by analytics)
CREATE TABLE betting_opportunities (
    id SERIAL PRIMARY KEY,
    stream_id VARCHAR NOT NULL,
    event_type VARCHAR NOT NULL,
    description TEXT NOT NULL,
    time_window_seconds INTEGER NOT NULL,
    suggested_odds DECIMAL(10,4) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_bets_user_stream ON bets(user_id, stream_id);
CREATE INDEX idx_bets_stream_status ON bets(stream_id, status);
CREATE INDEX idx_bets_created_at ON bets(created_at);
CREATE INDEX idx_analytics_stream_timestamp ON analytics_events(stream_id, timestamp);
CREATE INDEX idx_betting_opportunities_stream ON betting_opportunities(stream_id);
CREATE INDEX idx_betting_opportunities_expires ON betting_opportunities(expires_at);

-- Triggers for updating timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_balances_updated_at 
    BEFORE UPDATE ON user_balances 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); 